name: tecfix_frontend_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Actualizamos a Dart 3 para soportar las librerías modernas
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Dependencias de TecFix ---

  # Iconos estilo iOS (Standard)
  cupertino_icons: ^1.0.6

  # Para conectar con el Backend (API)
  http: ^1.2.0

  # Para guardar sesión (Token y Datos Usuario)
  shared_preferences: ^2.2.2

  # Para Cámara y Galería (Fotos)
  image_picker: ^1.0.7

  # Para Diseño Moderno (Tipografía) - ¡FALTABA ESTA!
  google_fonts: ^6.1.0

  # Para formato de Fechas
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter actualizado para Dart 3
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true